### ISSUE TITLE
crashing my project

### ISSUE THREAD

**Issue by aetherbound1** [Reun-Media/godot-levelblock#13]
I don't know what else to say, it just straight up crashes my project.

**Comment by Cryszon** [comment]
Hi! Would you mind providing more information:

- Your operating system
- Godot version
- Any error messages printed to console or saved to logs (see below)
- Other installed addons
- Does the crash happen when running the project or does it prevent you from opening the editor

It would help to check if there are any error messages in Godot log files. You can open the logs directory through Godot menu **Project -> Open User Data Folder**.

If the project crashes the editor before you can open it, you can find the logs by opening another project, selecting **Editor -> Open Editor Data/Settings Folder** and opening `app_userdata` folder to see all your projects.

You could also try temporarily moving the addon directory outside `addons` and/or manually editing `project.godot` to disable it.

**Comment by aetherbound1** [comment]
- windows 10
- 4.3
- (I will check soon)
- none
- when running the project

**Comment by Cryszon** [comment]
Closed due to no updates. If you still have problems, feel free to reopen and provide more information.
