### ISSUE TITLE
A way for the levelblock to be considered in the backing of Navmesh

### ISSUE THREAD

**Issue by Greaven-GitHub** [Reun-Media/godot-levelblock#14]
This plugin is awesome, the only problem is you can't bake any navmesh on the nodes, which makes it a lot harder to design enemy pathfinding on the nodes, unless you use AStar3D.

See [this thread](https://forum.godotengine.org/t/navmesh-not-generating/91842/3?u=greaven) response for more deatils on adding compatibility for navmesh in the plugin.

**Comment by Cryszon** [comment]
Navigation support is implemented in #15. Would you be willing to test the implementation in your project and report back with a comment to the PR?

You can get the updated version from `add-navigation-support` branch with Git or download it as a ZIP using [this link](https://github.com/Reun-Media/godot-levelblock/archive/refs/heads/add-navigation-support.zip).
