### ISSUE TITLE
Godot 4 update

### ISSUE THREAD

**Issue by Cryszon** [Reun-Media/godot-levelblock#9]
# Things to do
- [x] Update plugin to support Godot 4
  - #8
- [x] Create a separate branch for Godot 3 version
  - https://github.com/Reun-Media/godot-levelblock/tree/godot-3
- [x] Prepare CHANGELOG and README for Godot 4 release
  - #10
  - [x] Update CHANGELOG
  - [x] Mention 3.x branch in README
- [x] Release new version to Godot Asset Library
  - [x] Submit new version to Asset Library
  - [x] Update new Asset Library URL to README (badge and Getting Started section)
  - [x] Tag and create a new release
  - [x] Update commit hash in Godot Asset Library to match the release in GitHub
- [x] Update [Dungeon Crawler Movement tutorial's](https://www.youtube.com/watch?v=Vr-Fsd6M5Tk) description to mention Godot 4 version.
  - Maybe add a pinned comment as well.

**Comment by Cryszon** [comment]
# About Godot Asset Library submission

We need to submit a separate Godot 4 version of the asset.

> Godot version:
The version of the engine that the asset works with. Currently, it's not possible to have a single asset entry contain downloads for multiple engine versions, so you may need to re-submit the asset multiple times, with an entry for each Godot version it supports. This is particularly important when dealing with major versions of the engine, such as Godot 2.x and Godot 3.x.
- https://docs.godotengine.org/en/stable/community/asset_library/submitting_to_assetlib.html

**Comment by Hamzalopode** [comment]
"Update plugin to support Godot 4" Should be done now, you can create a separate branch for Godot 3 and change CHANGELOG for release 🔥

**Comment by OneginIII** [comment]
Seems good to me! I updated the screenshot with a similar one of the Godot 4 version.

Once the new version is available, I'll update the video info on YouTube.

**Comment by Hamzalopode** [comment]
Good job 🔥

**Comment by OneginIII** [comment]
I did the YouTube update. With that, the Godot 4 update is done.
